c4dt/omniledger

dynacred/package-lock.json, webserver/package-lock.json
Run `npm audit fix` in `webserver` and `dynacred`
Closes #11
=> applied npm audit fix

webserver/src/app/admin/contacts/add-darcinstance.html, webserver/src/app/admin/contacts/contacts.component.html, webserver/src/app/admin/contacts/contacts.component.ts, webserver/src/app/admin/contacts/show-darcinstance.html, webserver/src/app/app.module.ts
=> admin/contacts: improve handling of {group,action}

dynacred/src/Contact.ts, dynacred/src/Data.ts, webserver/src/app/admin/contacts/contacts.component.ts, webserver/src/app/c4dt/c4dt.component.html, webserver/src/app/c4dt/profile/profile.component.html, webserver/src/app/c4dt/profile/profile.component.ts
Re-use speed up improvements.
Closes #29
=> Picked up speed-improvements

webserver/src/app/api/v0/cas/login/login.component.ts, webserver/src/app/c4dt/c4dt.component.ts
=> correctly loading gData

.travis.yml
Last of c4dt/TODO#28 chain. Previous is #36.
* build conode, dynacred and webserver
* TODO test it: deploy dynacred to NPM, webserver to demonstrator
=> *: add travis

dynacred/.gitignore, dynacred/package-lock.json, dynacred/package.json, dynacred/src/Data.ts, dynacred/tsconfig.json, webapp/src/app/admin/contacts/add-darcinstance.html, webapp/src/app/admin/contacts/contacts.component.html, webapp/src/app/admin/contacts/contacts.component.ts, webapp/src/app/admin/contacts/signup-link.html, webapp/src/app/admin/contacts/user-cred.html, webapp/src/app/admin/status/status.component.html, webapp/src/app/admin/status/status.component.ts, webapp/src/app/admin/yourself/yourself.component.ts, webapp/src/app/api/v0/cas/login/login.component.ts, webapp/src/app/app.module.ts, webapp/src/app/c4dt/c4dt.component.ts, webapp/src/app/c4dt/profile/profile.component.html, webapp/src/app/c4dt/profile/profile.component.ts, webapp/src/app/register/register.component.html, webapp/src/app/register/register.component.ts, webapp/src/environments/environment.ts
Some improvements from the UI of the demonstrator, to have a nicer user experience:
- correctly go to the c4dt-subuser config
- removed some buttons added admin/c4dt links
New user-configuration for the admin, that allows to directly set the darc
the user will be in, also adding this darc to the user.
Only give 500 credits to new users, so they can only create 5 devices,
but not new users.
=> Make demonstrator nicer and add user-configuration

dynacred/src/Data.ts, dynacred/src/Defaults.ts, webapp/src/app/admin/contacts/contacts.component.ts, webapp/src/app/admin/status/status.component.ts, webapp/src/app/admin/yourself/yourself.component.ts, webapp/src/app/api/v0/cas/login/login.component.ts, webapp/src/app/app.component.ts, webapp/src/app/register/device/device.component.ts, webapp/src/app/register/register.component.ts
Remove many elements of `Defaults`. The remaining will be put in `config.{toml,ts}`.
=> Trim `Defaults`

dynacred/package-lock.json, webapp/package-lock.json
=> {webapp,dynacred}: npm i

mobile/app/lib/dynacred/Contact.ts, mobile/app/lib/dynacred/Data.ts, mobile/app/lib/test-data.ts, mobile/app/lib/user-data.ts, mobile/app/pages/lab/personhood/scan-atts/scan-atts-page.ts, mobile/app/pages/loading/loading-page.ts, mobile/app/pages/setup/1-present.ts, mobile/app/pages/setup/1-present.xml, mobile/package-lock.json, mobile/package.json
The webservice has a possibility of adding new devices to the identity. This
PR adds a button on the setup-page that can scan the QRcode of the new device.
It also fixes usage of 'new URL' which doesn't work in nativescript.
=> Adding a button to link as new device

.travis.yml, conode/Makefile
Adding some checks for the conode-docker.
=> Doing more checks

conode/Makefile, webapp/package-lock.json, webapp/package.json, webapp/src/app/admin/admin.component.html, webapp/src/app/admin/devices/device-show.html, webapp/src/app/admin/personhood/personhood.component.html, webapp/src/app/admin/personhood/personhood.component.ts, webapp/src/app/app-routing.module.ts, webapp/src/app/app.component.ts, webapp/src/app/app.module.ts, webapp/src/app/register/register.component.ts
In order to copy a device to the mobile app, it shows now the QRCode of the URL.
Additionally, the 'Secret' tab got replaced by a 'Personhood' tab that will show
some information about the personhood-data.
Deps on #65
=> Show QRCode for new devices

mobile/app/lib/user-data.ts, mobile/app/pages/lab/personhood/add-party/add-party-page.scss, mobile/app/pages/lab/personhood/add-party/add-party-page.ts, mobile/app/pages/lab/personhood/add-party/add-party-page.xml
This PR makes sure that iOS doesn't choke an any error in the
xml and css code, and that all the data is correctly shown
to the user.
=> Fix iOS display of addParty

.travis.yml, Makefile, conode/Makefile, dynacred/Makefile, dynacred/package-lock.json, dynacred/package.json, dynacred/src/Data.ts, dynacred/src/index.ts, webapp/.gitattributes, webapp/Makefile, webapp/package-lock.json, webapp/package.json, webapp/src/app/admin/contacts/contacts.component.ts, webapp/src/app/admin/devices/devices.component.ts, webapp/src/app/admin/secure/secure.component.ts, webapp/src/app/register/device/device.component.ts, webapp/src/app/register/register.component.ts, webapp/src/lib/Ui.ts, webapp/src/lib/dialog-transaction.ts
* Worked on the display of the device add/remove
* included the new code to have faster responses from the nodes
=> Nicer device change

mobile/BUGS, mobile/app/App_Resources/Android/src/main/AndroidManifest.xml, mobile/app/App_Resources/iOS/Info.plist, mobile/app/lib/cothority/byzcoin/byzcoin-rpc.ts, mobile/app/lib/cothority/network/connection.ts, mobile/app/lib/dynacred/Data.ts, mobile/app/lib/dynacred/personhood-rpc.ts, mobile/app/lib/test-data.ts, mobile/app/lib/user-data.ts, mobile/app/pages/home/meetup/meetup-page.ts, mobile/app/pages/lab/poll/poll-view.ts, mobile/app/pages/lab/ropasci/ropasci-page.ts, mobile/app/pages/lab/ropasci/ropasci-view.ts, mobile/app/pages/loading/loading-page.ts, mobile/app/pages/loading/loading-page.xml, mobile/app/pages/settings/settings-page.ts, mobile/app/pages/settings/settings-view.ts
Made it possible to have a 'training' phase to find the fastest node and then only use this one.
Pass all personhood-, ropasci-, and poll-services through the c4dt-node only.
=> Faster connection

mobile/.gitattributes, mobile/app/App_Resources/Android/src/main/res/values/strings.xml, mobile/app/i18n/en.json, mobile/app/i18n/fr.default.json, mobile/app/lib/personhood.ts, mobile/app/lib/user-data.ts, mobile/app/pages/home/home-page.ts, mobile/app/pages/home/home-page.xml, mobile/app/pages/home/personhood/personhood-page.ts, mobile/app/pages/home/personhood/personhood-page.xml, mobile/app/pages/identity/contacts/contacts-view.ts
* send coin -> invite
* removed meetup because of confusion
=> Small changes

mobile/app/lib/cothority/personhood/ro-pa-sci-instance.ts, mobile/app/lib/cothority/personhood/spawner-instance.ts, mobile/app/lib/dynacred/Contact.ts, mobile/app/lib/dynacred/Data.ts, mobile/app/lib/test-data.ts, mobile/app/lib/user-data.ts, mobile/app/pages/home/home-page.ts, mobile/app/pages/identity/challenge/challenge-page.ts, mobile/app/pages/lab/personhood/personhood-view.ts, mobile/app/pages/lab/ropasci/add/add-page.ts
* Add the calypso roster
* Fix the missing ltsID and ltsX for party-goers
=> using rps-calypso on the DEDIS blockchain

mobile/app/i18n/en.json, mobile/app/i18n/fr.default.json, mobile/app/pages/home/personhood/personhood-page.xml, mobile/app/pages/lab/personhood/personhood-view.ts
Changes discussed during the slides review
=> I18n improvements update

mobile/Makefile
make release
This command now makes all three releases: android 32-bit and 64-bit, as well as opens Xcode for ios
=> Adding more targets to makefile

webapp/src/app/bcviewer/bcviewer.component.ts, webapp/src/lib/dialog-transaction.ts
When a new transaction is shown, DialogTransactionComponent needs
to make sure that there is already a block in the cache, else
it needs to wait.
=> Correctly wait for first block

webapp/src/app/app.component.ts
If the device has been revoked from the signer-darc, it will
show so and remove the data from StorageDB.
Closes #25
=> Checking if device still has access

webapp/src/app/admin/contacts/contacts.component.ts, webapp/src/app/admin/contacts/user-cred.html
=> Removes debug-button

webapp/src/app/admin/contacts/contacts.component.html
Closes #26
I finally used
- `Create` - better than `Add` IMHO because it clearly designs that something so far unexisting will be created
- `Link` / `Unlink` - as proposed in #26 to link to existing darcs and to remove the link
=> Create - Link - Unlink

webapp/cas/service_validate.go
On `serviceValidate` success, also return the Alias contained in the `CredentialStruct`. Useful for setting a default name in the services.
=> webapp/cas: add Alias to attributes

webapp/src/app/api/v0/cas/login/login.component.ts
Add wordpress test server to login.
=> webapp/login: add c4dt.paperboy.ch

webapp/src/app/admin/contacts/add-contact.html, webapp/src/app/admin/contacts/add-darcinstance.html, webapp/src/app/admin/contacts/create-user.html, webapp/src/app/admin/contacts/create.html, webapp/src/app/admin/contacts/show-darcinstance.html, webapp/src/app/admin/contacts/signup-link.html, webapp/src/app/admin/contacts/transfer-coin.html, webapp/src/app/admin/contacts/user-cred.html, webapp/src/app/admin/devices/device-add.html, webapp/src/app/admin/devices/device-show.html, webapp/src/app/admin/manage-darc.html, webapp/src/app/admin/secure/calypso-show-access.html, webapp/src/app/admin/secure/calypso-upload.html, webapp/src/app/app.component.html, webapp/src/app/bcviewer/show-block.html, webapp/src/app/newuser/newuser.component.html, webapp/src/app/register/register.component.html, webapp/src/app/retry-load.html, webapp/src/index.html, webapp/src/lib/dialog-okcancel.html, webapp/src/lib/dialog-transaction.html
It's now directly in `index.html`.
=> webapp: use mat-typography

webapp/src/app/api/v0/cas/login/login.component.html, webapp/src/app/api/v0/cas/login/login.component.ts
Show transaction when pushing challenge, center the `/login`.
=> webapp/login/cas: improve style

dynacred/spec/contact.spec.ts, dynacred/spec/data.spec.ts, dynacred/src/Contact.ts, dynacred/src/Data.ts, webapp/src/app/admin/contacts/add-contact.html, webapp/src/app/admin/contacts/contacts.component.html, webapp/src/app/admin/contacts/contacts.component.ts, webapp/src/app/admin/contacts/create.html, webapp/src/app/admin/contacts/transfer-coin.html, webapp/src/app/admin/contacts/user-cred.html, webapp/src/app/admin/devices/device-add.html, webapp/src/app/admin/devices/device-recovery.html, webapp/src/app/admin/devices/device-show.html, webapp/src/app/admin/devices/devices.component.html, webapp/src/app/admin/devices/devices.component.ts, webapp/src/app/admin/manage-darc.html, webapp/src/app/admin/manage-darc.ts, webapp/src/app/admin/secure/calypso-upload.html, webapp/src/app/admin/secure/secure.component.ts, webapp/src/app/app.module.ts, webapp/src/lib/Ui.ts, webapp/src/lib/dialog-transaction.html, webapp/src/lib/dialog-transaction.ts
Simple recovery option that adds a new darc to the list of devices. If
the darc represents an organization, all signers from this organization
can recover the user.
=> Adds a recovery option

webapp/src/app/api/v0/cas/login/login.component.ts
=> webapp/login: matrix moved port

dynacred/src/Badge.ts, dynacred/src/Contact.ts, dynacred/src/Data.ts
fw of main commit of #146 
* rather use undefined than null
* now works with dedis/cothority#2041
=> dynacred/Contact: prepareInitialCred use undefined

webapp/src/app/api/v0/cas/login/login.component.ts
* need #146 to work
* something more to discribe?
=> webapp/login: add progress

dynacred/src/Contact.ts, webapp/src/app/admin/contacts/contact-info/contact-info.component.html, webapp/src/app/admin/contacts/contact-info/contact-info.component.ts, webapp/src/app/admin/contacts/contacts.component.html, webapp/src/app/admin/contacts/contacts.component.ts, webapp/src/app/app.module.ts
* dump pretty much every field of `Contact`
* as personhood is not set by default with a new user, we explicitly check for it
=> webapp/admin/contacts: more contact infos

webapp/src/app/api/v0/cas/login/login.component.html, webapp/src/app/api/v0/cas/login/login.component.ts
* follow procedure as documented in #137
* now need also DARC of action, to check auth against
* better/nicer use of enum inside html
=> webapp/api/cas/login: use checkAuth first

webapp/src/app/admin/admin.component.ts, webapp/src/app/admin/contacts/contacts.component.ts, webapp/src/app/admin/devices/devices.component.ts, webapp/src/app/admin/personhood/personhood.component.ts, webapp/src/app/admin/secure/secure.component.ts, webapp/src/app/admin/status/status.component.ts, webapp/src/app/admin/yourself/yourself.component.ts, webapp/src/app/c4dt/c4dt.component.ts, webapp/src/app/c4dt/partner/partner.component.ts, webapp/src/app/c4dt/profile/profile.component.ts, webapp/src/app/c4dt/welcome/welcome.component.ts, webapp/src/app/newuser/newuser.component.ts, webapp/src/app/register/device/device.component.ts, webapp/src/app/register/register.component.ts
=> Delete empyt component.css files

dynacred/src/Data.ts, dynacred/src/Storage.ts, webapp/src/app/app.component.ts, webapp/src/app/user-data.service.ts
=> Correctly display newuser page

webapp/src/app/c4dt/welcome/welcome.component.html
=> Fix link for members-only

dynacred/spec/contact.spec.ts, dynacred/spec/data.spec.ts, dynacred/src/Contact.ts, webapp/package-lock.json, webapp/src/app/admin/contacts/contacts.component.ts, webapp/src/app/admin/devices/devices.component.ts, webapp/src/app/register/device/device.component.ts, webapp/src/app/user-data.service.ts, webapp/src/lib/dialog-transaction.ts
=> Fixes some UI issues

conode/build/.gitignore, webapp/src/app/app-routing.module.ts, webapp/src/app/app.component.ts, webapp/src/app/app.module.ts, webapp/src/app/explorer/coin/coin.component.html, webapp/src/app/explorer/coin/coin.component.ts, webapp/src/app/explorer/credential/credential.component.html, webapp/src/app/explorer/credential/credential.component.ts, webapp/src/app/explorer/darc/darc.component.html, webapp/src/app/explorer/darc/darc.component.ts, webapp/src/app/explorer/explorer.component.html, webapp/src/app/explorer/explorer.component.ts
Adds an explorer to omniledger with links to other instances.
Instead of waiting for the full phonebook, already merging this now, so that it can be used with an upcoming update for the personhood-contract.
=> Simple explorer

dynacred/spec/contact.spec.ts, webapp/src/app/api/v0/cas/login/login.component.ts
replace all references to crypto with crypto-browserify
=> move to crypto-browserify

webapp/src/app/app.component.ts
=> Remove undefined in logging

dynacred/src/Badge.ts, dynacred/src/Contact.ts, dynacred/src/Data.ts, dynacred/src/KeyPair.ts, dynacred/src/personhood-rpc.ts, mobile/app/pages/lab/personhood/personhood-view.ts, webapp/Makefile
Mostly updates for personhood-related actions, plus some cleanups.
Depends on dedis/cothority#2165 and #191
=> Merging changes from mobile

mobile/Makefile, webapp/Makefile, webapp/src/app/app.component.html, webapp/src/app/app.component.ts, webapp/src/app/user-data.service.ts
=> Fixed Makefiles and no bcviewer for cas login

webapp/angular.json, webapp/package.json, webapp/src/app/app.component.html, webapp/src/app/app.component.ts
Add a version label to the page.
=> Adding version to display

mobile/app/pages/lab/personhood/add-party/add-party-page.xml
A leftover i18n that @cgrigis still had in his tree. :)
Replaces #153
=> i18n for add_party dialog

webapp/src/app/app.component.ts
As the registration needs the updateBlocks to be shown, it must come after enabling them.
=> Re-arrange loading system

mobile/app/i18n/en.json, mobile/app/lib/group-ui.ts, mobile/app/pages/lab/group/configure/configure-page.ts
- possibility to review the modifications made by a scanned group contract
- other small UI tweaks
=> Group Management of Organizers: UI enhancements

webapp/cas/config.go, webapp/package-lock.json, webapp/package.json, webapp/src/app/api/v0/cas/config.service.ts, webapp/src/app/api/v0/cas/login/login.component.html, webapp/src/app/api/v0/cas/login/login.component.ts, webapp/src/assets/.gitignore
* cas was using two config, which got out of sync
* now, it uses the same config, so adding a parsing for it
=> webapp/cas: use common config

webapp/cas/logout.go, webapp/cas/service_validate.go
Do match the service URL without Query or Fragment.
=> webapp/cas: match url without query

webapp/cas/cmd/cas/main.go
* add serviceValidate CASv2 call for apache:mod_auth_cas support
=> webapp/cas: add /serviceValidate

webapp/angular.json, webapp/package.json, webapp/src/app/admin/admin.component.html, webapp/src/app/admin/status/status.component.ts, webapp/src/lib/dialog-transaction.html, webapp/src/lib/dialog-transaction.ts, webapp/src/lib/show/show-darcinstance.html
adds a nicer gif-animation for the cothority
fixes wrong css-class name
removes calypso-tab
=> simple fixes

dynacred/package-lock.json, dynacred/package.json, dynacred/src/byzcoin/darcsBS.ts, dynacred/src/byzcoin/transactionBuilder.ts, dynacred/src/calypso.ts, dynacred/src/credentialStructBS.ts, dynacred/src/fetcher.ts, dynacred/src/keypair.ts, dynacred/src/spawnerTransactionBuilder.ts, dynacred/src/user.ts, webapp/package-lock.json, webapp/package.json, webapp/src/app/admin/admin.component.html, webapp/src/app/admin/contacts/contacts.component.ts, webapp/src/app/user.service.ts, webapp/src/lib/dialog-transaction.html, webapp/src/lib/dialog-transaction.scss
- using latest version of @dedis/cothority
- using isBuffer instead of 'instanceof', because the latter doesn't work well after minify
- improve calypso usage in dynacred
- allow values to be spawned
=> Backported handson changes

webapp/src/app/admin/contacts/contacts.component.ts, webapp/src/app/admin/contacts/create.html
When a darc-creation (group or action) is cancelled, don't create a darc.
Also correctly udpates the titles.
Closes #242
=> Allow cancelling of darc-creation

webapp/cas/cmd/cas-test/main.go
Make it clearer where the error is coming from by adding some context.
=> webapp/cas/cas-test: give ctx to every err msg

webapp/cas/README.md, webapp/cas/cmd/cas-test/main.go
update to support dynacred2 database instead of dynacred one.
=> webapp/cas: bump to dynacred2

webapp/cas/cmd/cas-test/main.go
=> cas/test: bump for new matrix UI

conode/Makefile, dynacred/package-lock.json, dynacred/package.json, webapp/package-lock.json, webapp/package.json, webapp/src/app/api/v0/cas/login/login.component.ts, webapp/src/app/app.component.ts, webapp/src/app/newuser/newuser.component.html, webapp/src/app/newuser/newuser.component.ts, webapp/src/assets/config.dedis.toml, webapp/src/lib/config.ts
Use the new email part of the personhood service that allows to:
- sign up a new user and send an email with the sign-up link
- recover an existing user with an existing email
=> Add signup and recover possibility

webapp/src/app/admin/contacts/contacts.component.ts
For once the javascript-error was useful...
=> Fix rewriting error

.github/workflows/deploy.yml, .github/workflows/lint-and-test.yml, webapp/.browserslistrc, webapp/angular.json
* only deploy on main branch (and don't run tests)
* build webapp in CI
* avoid building for old browsers
* fix `ng build --prod`
Closes #334
=> github/deploy: build locally

.github/workflows/deploy.yml, .github/workflows/lint-and-test.yml, dynacred/package-lock.json, dynacred/package.json, webapp/README.release.md, webapp/package-lock.json, webapp/package.json, webapp/src/assets/config.dedis.toml
Follows the PR c4dt/ansible-config#59 to:
- copy the config-files from the remote:www/assets
- install the cas-binary directly on the remote machine
- also updates the webapp/src/assets/config.dedis.toml, as it is used in make serve_dedis
=> Cleans up the deployment of omniledger

.github/workflows/deploy.yml
=> Correctly launch two commands with ssh
