c4dt/omniledger

dynacred/src/Contact.ts
dynacred/src/Data.ts
webserver/src/app/admin/contacts/contacts.component.ts
webserver/src/app/c4dt/c4dt.component.html
webserver/src/app/c4dt/profile/profile.component.html
webserver/src/app/c4dt/profile/profile.component.ts

This PR batches the transactions necessary to create an user, which makes the user
creation much faster. It puts all instructions in one ClientTransaction and then
sends this to the conodes.
It also removes a lot of double-loading for the contacts. On startup, it will only
load the credentialInstance of each contact, the rest has to be loaded when
needed.
Closes #24 
Closes #20

Batch transactions and other speedups

---

dynacred/src/Data.ts
dynacred/src/Defaults.ts
webserver/src/app/admin/status/status.component.ts
webserver/src/app/register/register.component.ts

- get the `Roster` configuration from `/assets/conodes.toml`
- because getting the `Roster` is a remote operation, it should be awaited now (as `Defaults` is not scoped, we can't `await` it before using it)

dynacred: get Roster from server's asserts

---

webserver/package-lock.json
webserver/package.json
webserver/src/assets/conodes.toml

PR for #30.
So for now, it's not generating `conodes.toml`, that'll be in a second phase, when c4dt/omniledger uses c4dt/services.

Reenable roster remplacement

---

webserver/src/app/api/v0/wordpress/login/login.component.html
webserver/src/app/api/v0/wordpress/login/login.component.spec.ts
webserver/src/app/api/v0/wordpress/login/login.component.ts
webserver/src/app/app-routing.module.ts
webserver/src/app/app.module.ts

* add call `/api/v0/wordpress/login`
* for now, `darcID` isn't used, we only check that the user is on the chain

webserver: add wordpress login

---

webserver/package-lock.json
webserver/package.json
webserver/src/karma.conf.js

Start of c4dt/TODO#28 chain.
* add Firefox launcher (using it on my side); we can use phantom-js instead, which I find more fit to a testing env, but to avoid breaking with Chrome-only users, for now, simply adding it
* by default now, karma will `singleRun`, so testing finishes (classique behavior of tests), to have the same behavior as before, one would `npm run test -- --watch` (or directly `ng test --watch`)

webserver: karma firefox and single run

---

dynacred/publish.sh

* remove `--link` (using `npm link` doesn't solve any of the issue I encontered, but maybe it is useful to someone)
* by default, publish to @dev, if an arg was given, publish to this one
* dynacred is public now

dynacred: rewrite publish.sh

---

.travis.yml

For unknown reasons, 'ng build --prod' does a more thorough test with regard
to private/public attributes than 'ng build' only.

test build --prod

---

webapp/Makefile
webapp/src/app/admin/contacts/show-darcinstance.html
webapp/src/app/api/v0/cas/login/login.component.ts
webapp/tsconfig.json

Darc.base_id is only the same as darc.id for version == 0
Switch to es6, so `user-data` can `super` on `Data`
Update darc used for matrix login

correctly show darc.base_id and switch to es6

---

dynacred/package.json

As it is, when I `npm i @c4dt/dynacred`, I get the following result:
```
$ tree node_modules/@c4dt/dynacred/
node_modules/@c4dt/dynacred/
├── bundle.min.js
├── package.json
└── README.md
0 directories, 3 files
```
This commit (actually a revert on `package.json`) appears to fix it for me. It seems this was changed recently, am I missing something?

Fix packaging for dynacred

---

webapp/package.json
webapp/src/app/admin/contacts/contacts.component.ts
webapp/src/app/admin/contacts/user-cred.html
webapp/src/app/app.component.ts
webapp/src/app/c4dt/partner/partner.component.html
webapp/src/app/c4dt/partner/partner.component.ts

The C4DT partners should not be able to chose the view and the groups from the user,
but this should be created automatically for them. If they _do_ want to influence
this, they have to use the /admin-interface.

remove view- and groups-choice from c4dt_partner createUser

---

webapp/src/app/register/device/device.component.ts

When adding a new device to an existing device in the browser, there needs
to be a check, like the registration.

Confirm overwriting of new device

---

webapp/src/lib/Ui.ts
webapp/src/lib/dialog-transaction.html
webapp/src/lib/dialog-transaction.ts

Didn't find a way to gen observable error inside a DialogRef, so any error return is really an error.

webapp/UI: fix showTx handling of Promise

---

webapp/cas/cmd/cas-stress/main.go

* headless is better
* go is weird with scoping and closures

webapp/cas/stress: use headless chrome, small fixes

---

.travis.yml
Makefile
conode/Makefile
conode/build/Dockerfile
conode/go.mod
dynacred/Makefile
mobile/Makefile
mobile/nodeify.sh
webapp/Makefile

This PR makes sure that all Makefiles can be used as they are supposed to be,
in order to:
- dynacred, mobile: build or prepare the directory
- conode, webapp: run the app in the directory
- dynacred, mobile, webapp: switch between libraries as source or as npms

Update Makefiles and helpers

---

dynacred/spec/contact.spec.ts
dynacred/src/Contact.ts

This makes it possible to easily retrieve the devices of a contact.
Useful if you want to use the public key(s) of a contact.

Adds Contact.getDevices

---

dynacred/Makefile
webapp/Makefile
webapp/tsconfig.json

When wanting to work directly on the source of cothority and kyber,
'make src' copies the latest source of these libraries directly into
the webapp- and dynacred-sources.

Fixing make src

---

mobile/nodeify_temporary_patch.patch

The completely black-magick patch for nodeify needs an addition for the
@c4dt/kyber module.

Also allow c4dt/kyber for crypto-browserify

---

dynacred/src/fetcher.ts

When an outdated LTS is stored in the user, it should still load.
This only puts a warning that the LTS is outdated, but continues to load
the user.

fix calypso error

---

dynacred/src/calypso.ts
webapp/src/app/bcviewer/bcviewer.component.ts
webapp/src/app/byz-coin.service.ts
webapp/src/app/explorer/explorer.component.ts

Forward-link verification is quite costly in javascript.
To speed up following the blockchain, the forward-links
are trusted and not verified.

Trust nodes

---

dynacred/spec/addressbook.spec.ts
dynacred/spec/signers.spec.ts
dynacred/spec/simul/itest.ts
dynacred/spec/support/conodes.ts
dynacred/src/byzcoin/darcsBS.ts
dynacred/src/credentialSignerBS.ts
dynacred/src/index.ts
dynacred/src/migrate.ts
dynacred/src/spawnerTransactionBuilder.ts
webapp/src/app/admin/devices/devices.component.html
webapp/src/app/admin/devices/devices.component.ts

Previously a recovery-darc has been added to both the _sign and the evolve
rule of the signer-darc. Which meant that a recovery darc was also evaluated
for siging, which is confusing.
Even though a recovery signature can theoretically recover the ID and then
use it to sign, it should not be the default behaviour.
This PR makes it so that recovery-darcs are only added to the _evolve rule
of the signer-darc, and also adds a button to change the behaviour of
the recovery-entry in the UI.

Don't allow recoveries to sign

---

webapp/src/app/app.component.ts
webapp/src/app/app.module.ts
webapp/src/app/byz-coin.service.ts
webapp/src/app/db-error-dialog/db-error-dialog.component.html
webapp/src/app/db-error-dialog/db-error-dialog.component.ts
webapp/src/lib/dialog-okcancel.html

If the browser is in private mode or refuses to use cookies, it doesn't
allow to store data. But this feature is needed by OmniLedger login.
This PR shows an explanation in that case and points to a c4dt.org
article with more information.
closes dedis/cothority#2415

Warn if storage cannot be used

---

.travis.yml
webapp/cas/cmd/cas-test/main.go

* with new matrix, the classname wasn't valid anymore
* sadly, I didn't find a better way to select this `div` element
* `JSON.parse` doesn't return an array (anymore) in chrome
* also improve the error message returned when the script fails to execute

Fix cas-test for matrix

---

webapp/src/app/admin/contacts/contacts.component.ts
webapp/src/app/admin/devices/devices.component.ts
webapp/src/app/newuser/newuser.component.html
webapp/src/lib/config.ts

Now that there will be two installations - one on demo.c4dt.org to recover the accounts,
and one on login.c4dt.org - there needs to be a way to force the creation of the links
to the new installation.
This PR adds a field 'BaseURL' to the config.toml that will be used to create the links for
new users and recovery accounts.

Add baseurl configuration

---

webapp/cas/cmd/cas-test/main.go

Chrome is unstable and might fail on headless systems. Disabling GPU rendering which seems more reliable.
The root cause of why the stats suddenly failed is still unknown. We might never know. Life has such mysteries.

webapp/cas-test: disable GPU

---

webapp/src/app/api/v0/cas/login/login.component.html
webapp/src/app/api/v0/cas/login/login.component.ts

The StateT enum has been expanded to provide a new state that can be interpreted by Angular. I kept it very straightforward and barebones so that it behaves consistently with the way the other messages do.

adds HTML message on 'no such service' exception when connection via CAS

---

.travis.yml

It didn't deploy with the error
```
Skipping a deployment with the script provider because this branch is not permitted: main
```
So I guess it needs to be on the same line...

Deploy on main

---

dynacred/src/credentialSignerBS.ts
dynacred/src/credentialStructBS.ts
dynacred/src/user.ts
dynacred/src/userSkeleton.ts
webapp/src/app/admin/contacts/contacts.component.ts

Currently when recovering a user, it tries to:
1. update the signer-darc of the user
2. insert the device in the list of the user
But as of #263, recoveries are only allowed to evolve the user-signer-darc,
but not to sign on its behalf. So the two steps need to be signed by
different signers:
1. can be signed by the user that does the recovery
2. must be signed by the new ephemeral key

Correctly recover user

---

webapp/src/assets/config.dedis.toml

The ansible-config defines the names of the conode.c4dt.org and conode2.c4dt.org differently.

Use new names
